name: i_am_groot
description: A new Flutter project.

publish_to: 'none' # Tidak dipublikasikan ke pub.dev

version: 1.0.0+1 # Versi aplikasi

environment:
  sdk: '>=3.0.0 <4.0.0' # Versi SDK Flutter yang didukung

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2 # Ikon tambahan bergaya iOS

dev_dependencies:
  flutter_test:
    sdk: flutter # Library untuk pengujian aplikasi

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/im_blue.png
    - assets/baby_blue.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/baby_blue.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/baby_blue.png"
