name: i_am_groot
description: A new Flutter project.

publish_to: 'none' # Tidak dipublikasikan ke pub.dev

version: 1.0.0+1 # Versi aplikasi

environment:
  sdk: '>=3.0.0 <4.0.0' # Versi SDK Flutter yang didukung

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2 # Ikon tambahan bergaya iOS

dev_dependencies:
  flutter_test:
    sdk: flutter # Library untuk pengujian aplikasi

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0 # Linter untuk menjaga kualitas kode

  flutter_launcher_icons: ^0.13.1 # Plugin untuk mengganti ikon aplikasi

flutter:
  uses-material-design: true # Mengaktifkan Material Design

  assets:
    - assets/im_blue.png # Gambar yang digunakan dalam aplikasi
    - assets/baby_blue.png # Gambar lain yang digunakan

flutter_icons:
  android: true # Mengaktifkan ikon khusus untuk Android
  ios: true # Mengaktifkan ikon khusus untuk iOS
  image_path: "assets/baby_blue.png" # Ikon utama aplikasi
  adaptive_icon_background: "#ffffff" # Warna latar belakang ikon adaptif
  adaptive_icon_foreground: "assets/baby_blue.png" # Gambar ikon adaptif
